# Site
repository: mvdmeij/github.io
# favicon: images/favicon.ico

# Personal info
name: Danielle Franke 
title: Java Developer
email: danielle.franke91@gmail.com      
website: dfranke.nl

# Social links
#dockerhub_username: mvdmeij
github_username: insertnaam
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: 
linkedin_username: daniellefranke
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hoi ik ben Danielle, de enige echte commmunicatie specialist going JAVA DEV. Wil jij ook dat ik coole dingen bouw? NEEM MIJ DAN GVD AAn

  Ik ben erg goed in:  <mark>onderzoeken</mark> en <mark>lachen</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in development and operations engineering some of my other interests and hobbies are: 
   - Boulderen 
   - Tekenen
   - Leuke dingen doen met vriendinnen
   - Drankjes doen

# Footer
footer_show_references: false 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:

theme: jekyll-theme-minimal